Add steps to prevent updating badging if this is a fork

diff --git a/.github/workflows/Build.yaml b/.github/workflows/Build.yaml
--- a/.github/workflows/Build.yaml
+++ b/.github/workflows/Build.yaml
@@ -226,7 +226,15 @@ jobs:
 
       - name: Check badging
         id: check_badging
+        continue-on-error: true
         run: ./gradlew :app-compose:checkMarketReleaseBadging
+
+      - name: Prevent updating badging if this is a fork
+        id: checkfork_badging
+        continue-on-error: false
+        if: steps.check_badging.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          echo "::error::Badging check failed, please create a PR in your fork first." && exit 1
 
       - name: Update badging if verification failed and it's a PR
         id: update_badging
